version: 0.0
os: linux 
files:
  - source: /
    destination: /srv/www/pyapp
permissions:
  - object: /srv/www/pyapp
    owner: ubuntu
    mode: "0755"
hooks:
  AfterInstall:
    - location: bash/install.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: bash/start.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: bash/check.sh
      timeout: 60
      runas: ubuntu
