version: 0.2

env:
  variables:
    # enables continuous integration settings where applicable
    CI: true

phases:
  install:
    commands:

  pre_build:
    commands:
      # placeholder
  build:
    commands:
      - python3 -m venv venv
      - . venv/bin/activate
      - pip3 install -r requirements.txt
      - printenv
  post_build:
    commands:
      - ./venv/bin/gunicorn -b localhost:8000 application -D
      #- ./bash/find_gunicorn.sh
      - curl localhost:8000
      - ./bash/test_rekog.sh
      - ./bash/test_rxdata.sh
artifacts:
  files:
    - '**/*'