version: 0.2

env:
  variables:
    # enables continuous integration settings where applicable
    CI: true

phases:
  install:
    commands:

  pre_build:
    commands:
      # placeholder
  build:
    commands:
      - python3 -m venv venv
      - . venv/bin/activate
      - pip3 install -r requirements.txt
      - printenv
  post_build:
    commands:
      - ./venv/bin/gunicorn -b localhost:8000 application -D
      - sleep 1
      - ./bash/find_gunicorn.sh
      - sleep 1
      - curl -4 'http://localhost:8000'
      - sleep 1
      - curl localhost:8000/rekog
      - sleep 1
      - curl localhost:8000/rxdata
      - sleep 1
artifacts:
  files:
    - '**/*'