version: 0.2

env:
  variables:
    # enables continuous integration settings where applicable
    CI: true

phases:
  install:
    commands:

  pre_build:
    commands:
      # placeholder
  build:
    commands:
      - python3 -m venv venv
      - . venv/bin/activate
      - pip3 install -r requirements.txt
      - gunicorn -b 0.0.0.0:8000 application -D --forwarded-allow-ips "*"
  post_build:
    commands:
      - curl localhost:8000
      - sleep 1
      - curl localhost:8000/rekog
      - sleep 1
      - curl localhost:8000/rxdata
      - sleep 1
artifacts:
  files:
    - '**/*'